	CREATE TABLE EMPLOYEES_AUDIT (
ID INT AUTO_INCREMENT PRIMARY KEY,
EMPLOYEENUMBER INT NOT NULL,
LASTNAME VARCHAR(50) NOT NULL,
CHANGEDAT DATETIME DEFAULT NULL,
ACTION VARCHAR(50) DEFAULT NULL);
CREATE TRIGGER before_employee_update
BEFORE UPDATE ON EMPLOYEES
FOR EACH ROW
INSERT INTO EMPLOYEES_AUDIT SET ACTION='update',
employeenumber=OLD.employeenumber,
lastname=OLD.LASTNAME,
CHANGEDAT=NOW();
SHOW TRIGGERS;
UPDATE EMPLOYEES SET LASTNAME='Akriti' WHERE employeenumber=1056;
